### ISSUE TITLE
SanPlus::from_move needs a mutable Position?

### ISSUE THREAD

**Issue by marcusbuffett** [niklasf/shakmaty#51]
I'm confused by the signature of from_move for `SanPlus`, it takes a `mut Position`, which doesn't seem necessary, and is tripping me up a bit when using the library.

Looking at the source, I see this:

https://docs.rs/shakmaty/latest/src/shakmaty/san.rs.html#608

Which also confuses me, why is  `pos.play_unchecked(m);` called in there? 

My assumption would be that from_move would just take a &Position and a &Move, and then return a SanPlus, not play any moves or require a mutable Position.

Thank you for the excellent library, I wouldn't have been able to write the backend of my chess site in Rust without it.

**Comment by niklasf** [comment]
The implementation plays the move, to look at the resulting position, and test if the move has given check/checkmate.

Since the caller would not expect any moves to be played, the method intentionally consumes `pos`, instead of taking it by reference. The `mut` is not part of the [publicly visible signature](https://docs.rs/shakmaty/latest/shakmaty/san/struct.SanPlus.html#method.from_move).

Some (but not all) use cases now require `pos.clone()`. If the method would do the `pos.clone()` internally, there would be no way to avoid the clone in the other cases.

If you intend to play the move yourself anyway, for example in a loop, [`from_move_and_play_unchecked()`](https://docs.rs/shakmaty/latest/shakmaty/san/struct.SanPlus.html#method.from_move_and_play_unchecked) combines both efficiently.

**Comment by marcusbuffett** [comment]
That makes a lot of sense why it needs to be like that. Thanks for the clarification, and thanks again for the library :)
