### ISSUE TITLE
Bug: Missing En Passant capture in legal move generation

### ISSUE THREAD

**Issue by kirillbobyrev** [niklasf/shakmaty#54]
Position: `q6k/8/8/3pP3/8/8/8/7K w - d6 0 1`

Code (same as before):

```rust
use shakmaty::{CastlingMode, Chess, Position};

fn main() {
    let shakmaty_setup: shakmaty::fen::Fen = "q6k/8/8/3pP3/8/8/8/7K w - d6 0 1"
        .parse()
        .expect("If we parsed a position, it should be parsed by shakmaty, too.");
    let shakmaty_position: Chess = shakmaty_setup
        .position(CastlingMode::Standard)
        .expect("Oh-oh, this is not a legal position!");
    println!("{:?}", shakmaty_position.legal_moves());
}
```

Generated moves:

```
[Normal { role: Pawn, from: E5, capture: None, to: E6, promotion: None }, Normal { role: King, from: H1, capture: None, to: G1, promotion: None }, Normal { role: King, from: H1, capture: None, to: G2, promotion: None }, Normal { role: King, from: H1, capture: None, to: H2, promotion: None }]
```

This is missing move is `EnPassant { from: E5, to: D6 }`. This is the move that my engine has but shakmaty misses right now (latest version).

**Comment by niklasf** [comment]
Wouldn't this remove the d5 pawn, uncovering check?

**Comment by kirillbobyrev** [comment]
Oops, you're right, sorry!

**Comment by niklasf** [comment]
I guess it's a fair assumption that the double-pushed pawn can not be blocking a diagonal check. So you could argue that shakmaty should reject the position at the validation stage.

**Comment by kirillbobyrev** [comment]
Good point, though I think it would require some complex position correctness checking.

**Comment by kirillbobyrev** [comment]
I guess, the complexity with en-passant is that it is the only "forcing" FEN field that actually tells what the previous move was and all checks related to it need to deal with this "history".

**Comment by niklasf** [comment]
Yeah. The general policy I have for shakmaty is:

1. Acknowledge that it does not reject all unreachable positions (no proof game checking)
2. But detect positions that can cause problems with other software (especially popular engines like Stockfish)
3. Implement shakmaty itself so that move generation is robust even in those problematic positions (and offer a way to [ignore some validation](https://docs.rs/shakmaty/latest/shakmaty/struct.PositionError.html#method.ignore_impossible_check)).

#54: Stockfish is doing fine on this issue, so leaning towards not detecting this case (2). shakmaty itself works fine in this case.

#53: Stockfish does not correctly handle the impossible position, but shakmaty fails at (2). shakmaty itself also fails at 3.
